### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by xekc** [davidmz/BetterFeed#1]
Chrome Version 42.0.2311.135 (64-bit) / Mac, Tampermonkey v3.10.109 stable.

https://dl.dropboxusercontent.com/u/490558/4.png
https://dl.dropboxusercontent.com/u/490558/3.png
https://dl.dropboxusercontent.com/u/490558/2.png
https://dl.dropboxusercontent.com/u/490558/1.png

Никаких видимых эффектов от установки скрипта не происходит, по колесу бил, под капот смотрел, переустанавливал, перезапускал браузер.

Что делать?

V.

**Comment by davidmz** [comment]
А в консоли что-нибудь видно? Ctrl+Shift+J

**Comment by xekc** [comment]
A! Видно: Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
/js/config.js?v=2e1f942bd62a00960496a01ff08456da2c955266:95 Attempting URL transition to /xekc

Полез копаться в экстеншнах, нашёл Privacy Badger, который конфликтовал с HTTPs Everywhere и поэтому не выводился, но тем не менее блокировал подгрузку JS. 

Сделал в нём exception, всё заработало, спасибо!

**Comment by davidmz** [comment]
О как бывает:)
