### ISSUE TITLE
lightbox.js:70 Uncaught TypeError: Cannot read property '_att' of undefined

### ISSUE THREAD

**Issue by dandaka** [davidmz/BetterFeed#15]
1. https://freefeed.net/bifurcafe/5bc566cc-a323-4a1a-a00d-4b7df2e2acdd
2. Кликаем на фотку
3. Зум не срабатывает
4. Ошибка в стеке http://take.ms/QciTL

**Comment by davidmz** [comment]
Про всё это надо писать в BF2. Но спасибо, исправлю.

**Comment by dandaka** [comment]
Тогда может в README поставить ссылочку на BF2?

**Comment by davidmz** [comment]
Сделал.

**Comment by dandaka** [comment]
А как поставить новую версию BF2? У меня в Tampermonkey 2.1.1 судя по dashboard. Она же последняя версия. В dashboard TM она указана как "последнее обновление 22d назад".

https://raw.githubusercontent.com/davidmz/BetterFeed2/master/build/better-feed.user.js

Здесь версия такая же

**Comment by davidmz** [comment]
@dandaka Не надо смотреть в TamperMonkey. Надо открыть настройки БФ и внизу нажать кнопку «Проверить обновления».
