### ISSUE TITLE
Add warnings to BetterFeed options that don't work on mobile

### ISSUE THREAD

**Issue by smallq-git** [davidmz/BetterFeed#3]
Since it's now possible to use BetterFeed without any extensions, some users might want to use it on their mobile devices. However, some options are not available there. It will be good to warn that some options will not be available.

Options include:
- ^^^ to indicate comment (no ctrl on mobile)
- line-breaks in texts (no shift on mobile)

**Comment by davidmz** [comment]
Я не понимаю, как это правильно описать, и надо ли это делать вообще. Опция переводов строк управляет не только их вставкой в поле ввода, но и отображением в уже существующих постах и комментах (в том числе на мобильных). С ^^^ то же самое. Мне кажется, тут нет смысла что-то дополнительно приписывать.
