### ISSUE TITLE
Addressing user (@user) doesn't work if not in the beginning of comment

### ISSUE THREAD

**Issue by smallq-git** [davidmz/BetterFeed#7]
1. Log in as user with Betterfeed enabled.
2. On a post with comments open a new comment.
3. Write something.
4. Click comment bubble for some comment above - note that address is added to the comment field.
5. Press Enter or click Post.

Expected: comment is posted with address even if it's not in the beginning of the line.
Actual: comment is posted but address is removed.

Note: Address is retained if entered manually, or if it was entered first and then comment was added before it.

**Comment by davidmz** [comment]
Спасибо! Но у Вас это точно воспроизводится при нажатии на кнопку “Post”? Я это вижу только при отправке комментария Enter-ом.

Пока это выглядит как проблема эмбера, но я ещё покопаюсь.
