### ISSUE TITLE
Lonely bracket is moved to the next line 

### ISSUE THREAD

**Issue by smallq-git** [davidmz/BetterFeed#8]
![image](https://cloud.githubusercontent.com/assets/7983303/8710389/0ff8b16e-2b52-11e5-80de-075f953ecc35.png)

On peppa:
![image](https://cloud.githubusercontent.com/assets/7983303/8710468/abf9acb2-2b52-11e5-8092-7fc1accc9e2f.png)
https://micropeppa.freefeed.net/cheese/c5721d11-6a7a-4498-99ea-d20115a7f864

**Comment by davidmz** [comment]
Что-то у меня не воспроизводится. Это в каком браузере?

**Comment by smallq-git** [comment]
Сейчас я этого тоже не вижу. Закрываю ишью.

**Comment by smallq-git** [comment]
Поймала: это происходит в индивидуальном фиде (юзера или группы), при вьюпорте больше 1024, когда комменты - облачка или юзерпики. Коммент должен быть визуальной ширины в 77 кириллических символов (для латиницы - 89 символов).

Примеры: 
группа Сыр: https://micropeppa.freefeed.net/cheese (пост про безумно длинное описание группы)
тестюзер2: https://micropeppa.freefeed.net/testuser2 (пост user3, I hope you're enjoying this :-P)
